#!/usr/bin/env python3
"""
Task 2: Fit background angular toy (cosThetaK, cosThetaL)

Implements:
  i)   2D PDF for cosThetaK & cosThetaL (stolen from genbkg/generator.py)
  ii)  Read background ROOT sample (pattern stolen from angularfitter.py)
  iii) Fit PDF to background data (Minuit; similar to angularfitter.py)
  iv)  Store fit result + compare to generation params
  v)   Make two PNG figures: cosThetaK and cosThetaL with data + fit overlay

Usage example:
  python fitter/backgroundfitter.py \
      --data genbkg/bkg_toy.root \
      --tree background \
      --params genbkg/background_params.json \
      --outdir plots/backgroundfit \
      --nbins 50
"""

import argparse
import json
import os

import numpy as np
import uproot
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import zfit

try:
    import mplhep
    mplhep.style.use(mplhep.style.LHCb2)
    _HAVE_MPLHEP = True
except Exception:
    _HAVE_MPLHEP = False


def parse_args():
    ap = argparse.ArgumentParser(description="Fit background angles cosThetaK/cosThetaL with Legendre PDFs.")
    ap.add_argument("--data", required=True, help="Input ROOT file (generated by genbkg/generator.py)")
    ap.add_argument("--tree", default="background", help="TTree name in ROOT file (default: background)")
    ap.add_argument("--params", default="genbkg/background_params.json",
                    help="JSON params used in generator (default: genbkg/background_params.json)")
    ap.add_argument("--outdir", default="plots/backgroundfit", help="Output directory")
    ap.add_argument("--nbins", type=int, default=50, help="Number of bins for 1D plots")
    ap.add_argument("--seed", type=int, default=0, help="Random seed for reproducibility")
    return ap.parse_args()


def load_truth_params(params_json_path: str):
    """
    generator.py reads: json.load(f)["parameters"]
    so we mirror that exactly.
    """
    with open(params_json_path, "r") as f:
        d = json.load(f)
    return d["parameters"]


def read_background_angles(root_path: str, tree_name: str):
    """
    Mirror angularfitter.py style:
      with uproot.open(args.data) as f:
          datai = f["..."].arrays(library="pd")
          datai["cosl"] = datai["cosThetaL"]
          datai["cosh"] = datai["cosThetaK"]
    Only need angles, generator saves them as:
      cosThetaK, cosThetaL
    """
    with uproot.open(root_path) as f:
        df = f[tree_name].arrays(library="pd")

    # match angularfitter naming convention
    df["cosh"] = df["cosThetaK"]
    df["cosl"] = df["cosThetaL"]

    df = df[["cosh", "cosl"]].dropna()
    return df


def save_fit_result_json(outpath: str, result):
    """
    Save in a simple JSON format
    """
    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    out = {}
    for p, info in result.params.items():
        # result.hesse() stores error in info["hesse"]["error"]
        err = None
        if "hesse" in info and "error" in info["hesse"]:
            err = float(info["hesse"]["error"])
        out[p.name] = {"value": float(info["value"]), "error": err}
    with open(outpath, "w") as f:
        json.dump(out, f, indent=2, sort_keys=True)


def plot_1d_with_fit(xdata, proj_pdf, xlabel, outpath, nbins=50, title=None):
    os.makedirs(os.path.dirname(outpath), exist_ok=True)

    xmin, xmax = -1.0, 1.0
    counts, edges = np.histogram(xdata, bins=nbins, range=(xmin, xmax))
    centers = 0.5 * (edges[:-1] + edges[1:])
    widths = (edges[1:] - edges[:-1])
    N = len(xdata)

    # data error bars
    yerr = np.sqrt(np.maximum(counts, 1.0))

    # smooth curve
    x = np.linspace(xmin, xmax, 800)
    pdf_vals = proj_pdf.pdf(x).numpy()  # normalized density
    # convert density -> expected events per bin width
    binw = (xmax - xmin) / nbins
    y = pdf_vals * N * binw

    plt.figure()
    plt.errorbar(centers, counts, yerr=yerr, xerr=widths / 2.0, fmt=".", label="Toy data")
    plt.plot(x, y, label="Fit", color="k")

    plt.xlabel(xlabel, ha="right", x=1.0)
    plt.ylabel(f"Events / {binw:.2f}", ha="right", y=1.0)
    if title:
        plt.title(title)
    plt.xlim(xmin, xmax)
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath, dpi=200)
    plt.close()


def main():
    args = parse_args()

    np.random.seed(args.seed)
    zfit.settings.set_seed(args.seed)
    zfit.settings.set_verbosity(10)

    os.makedirs(args.outdir, exist_ok=True)

    # (ii) Read background sample
    df = read_background_angles(args.data, args.tree)
    print(f"Read {len(df)} events from {args.data}:{args.tree}")

    # (i) Define 2D PDF for (cosThetaK, cosThetaL) stolen from generator.py
    # generator.py uses:
    #   cosh = zfit.Space('cosThetaK', limits=(-1.0, 1.0))
    #   cosl = zfit.Space('cosThetaL', limits=(-1.0, 1.0))
    #   pdf_cosh = zfit.pdf.Legendre(obs=cosh, coeffs=[a1_cosh, a2_cosh])
    #   pdf_cosl = zfit.pdf.Legendre(obs=cosl, coeffs=[a1_cosl, a2_cosl])
    #   pdf_bkg = ProductPDF([...pdf_cosh, pdf_cosl...], obs=space)

    cosh = zfit.Space("cosh", limits=(-1.0, 1.0))
    cosl = zfit.Space("cosl", limits=(-1.0, 1.0))
    angles = cosh * cosl

    truth = load_truth_params(args.params)

    # Parameters
    a1_cosh = zfit.Parameter("a1_cosh", truth["a1_cosh"], -5.0, 5.0)
    a2_cosh = zfit.Parameter("a2_cosh", truth["a2_cosh"], -5.0, 5.0)
    a1_cosl = zfit.Parameter("a1_cosl", truth["a1_cosl"], -5.0, 5.0)
    a2_cosl = zfit.Parameter("a2_cosl", truth["a2_cosl"], -5.0, 5.0)

    pdf_cosh = zfit.pdf.Legendre(obs=cosh, coeffs=[a1_cosh, a2_cosh])
    pdf_cosl = zfit.pdf.Legendre(obs=cosl, coeffs=[a1_cosl, a2_cosl])

    pdf_ang = zfit.pdf.ProductPDF([pdf_cosh, pdf_cosl], obs=angles)

    # Build zfit dataset from pandas (matches angularfitter pattern)
    data = zfit.Data.from_pandas(df, obs=angles)

    # sanity checks similar to angularfitter
    vals = pdf_ang.pdf(data).numpy()
    assert np.all(vals > 0), "PDF returned non-positive values on data"
    assert not np.any(np.isnan(vals)), "PDF returned NaNs on data"
    assert not np.any(np.isinf(vals)), "PDF returned infs on data"

    # (iii) Fit the PDF to data
    loss = zfit.loss.UnbinnedNLL(model=pdf_ang, data=data)
    minimizer = zfit.minimize.Minuit()
    result = minimizer.minimize(loss)
    result.hesse()  # uncertainties

    print("\nFit summary:")
    print(result)

    # (iv) Store fit results + compare to truth
    out_json = os.path.join(args.outdir, "background_angle_fit.json")
    save_fit_result_json(out_json, result)

    print("\nTruth vs Fit (value ± hesse error):")
    for par in [a1_cosh, a2_cosh, a1_cosl, a2_cosl]:
        fitv = float(result.params[par]["value"])
        fite = result.params[par]["hesse"]["error"]
        tv = float(truth[par.name])
        print(f"  {par.name:7s}: truth={tv: .6g}   fit={fitv: .6g} ± {float(fite):.3g}")

    # (v) Create two figures (PNG): cosThetaK and cosThetaL with fit overlay
    # Use projection PDFs exactly like angularfitter uses create_projection_pdf
    proj_cosh = pdf_ang.create_projection_pdf(obs=cosh)
    proj_cosl = pdf_ang.create_projection_pdf(obs=cosl)

    plot_1d_with_fit(
        xdata=df["cosh"].to_numpy(),
        proj_pdf=proj_cosh,
        xlabel=r"$\cos(\theta_K)$",
        outpath=os.path.join(args.outdir, "cosThetaK_data_vs_fit.png"),
        nbins=args.nbins,
        title="Background: cosThetaK (toy vs fitted Legendre PDF)"
    )

    plot_1d_with_fit(
        xdata=df["cosl"].to_numpy(),
        proj_pdf=proj_cosl,
        xlabel=r"$\cos(\theta_L)$",
        outpath=os.path.join(args.outdir, "cosThetaL_data_vs_fit.png"),
        nbins=args.nbins,
        title="Background: cosThetaL (toy vs fitted Legendre PDF)"
    )

    print(f"\nWrote:\n  {out_json}\n  {os.path.join(args.outdir,'cosThetaK_data_vs_fit.png')}\n  {os.path.join(args.outdir,'cosThetaL_data_vs_fit.png')}")


if __name__ == "__main__":
    main()
